# Generated by Django 5.1.4 on 2025-01-07 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='тип продукта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/product/%Y/%m/%d', verbose_name='images_product_class')),
            ],
            options={
                'verbose_name': 'Класс продукта',
                'verbose_name_plural': 'Классы продуктов',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/product/%Y/%m/%d', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображения продуктов',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Скидка (%)')),
                ('in_stock', models.BooleanField(default=True, verbose_name='в наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='category.category', verbose_name='Категория')),
                ('subcategories', models.ManyToManyField(blank=True, related_name='products', to='category.subcategory', verbose_name='Подкатегории')),
                ('product_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.productclass', verbose_name='Класс продукта')),
                ('images', models.ManyToManyField(related_name='products', to='product.productimage', verbose_name='Изображения продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['id'],
            },
        ),
    ]
