# Generated by Django 5.1.4 on 2025-01-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Класс продукта'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название изображения продукта'),
        ),
    ]
