# Generated by Django 5.1.4 on 2025-01-08 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options_alter_subcategory_options_and_more'),
        ('product', '0004_alter_product_product_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='category.category', verbose_name='Категория продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='products', to='category.subcategory', verbose_name='Подкатегории продукта'),
        ),
    ]
